name: Draft PDF
on:
  push:
    paths:
      - 'paper.md'
      - 'paper.bib'

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/openjournals/draft-pdf:latest
        with:
          args: 'paper.md'
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf