name: Build JOSS PDF
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: |
          docker run --rm -v ${{ github.workspace }}:/data ghcr.io/openjournals/draft-pdf:latest paper.md
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf